config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :priorities
  mount Maily::Engine, at: '/maily'
  ActiveAdmin.routes(self)
  resources :customer_vendors
  resources :pricing_categories
  resources :customer_companies
  resources :vehicles
  resources :companies do
    get 'search_suggestions', on: :collection
  end
  resources :notify_types
  resources :notifications
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :upload_categories
  resources :franchise_users
  resources :franchises
  resources :vendor_upload_types
  resources :tracker_tasks
  resources :trackers
  resources :assignment_types
  resources :referral_types
  resources :corporate_referral_types
  resources :contacts
  devise_for :users
  resources :articles
  resources :franchise_zipcodes
  resources :oncalls do
    collection {post :sort}
  end
  resources :forms
  resources :vendor_categories
  resources :vendors do
    resources :vendor_uploads
  end
  resources :phones
  resources :addresses
  resources :calls
  resources :consumables
  resources :chemicals
  post 'calls/precall-lookup' => 'calls#precall_lookup'
  post 'calls/precall-webhook' => 'calls#precall'
  post 'calls/postcall-webhook' => 'calls#postcall'
  get 'users/list' => 'users#list'
  resources :users do
    patch 'link_tsheets_user'
  end
  resources :states
  resources :agents
  resources :adjusters

  get 'adwords' => 'adwords#index'
  get 'jobs/list' => 'jobs#list'
  get 'jobs/for_table' => 'jobs#for_table'
  get 'jobs/index_search' => 'jobs#index_search'
  get 'jobs/search' => 'jobs#search', as: :job_search
  get 'jobs/:id/calls' => 'jobs#calls', as: :job_calls
  get 'jobs/:id/calls/new' => 'jobs#add_call', as: :new_job_call
  post 'jobs/:id/calls' => 'jobs#create_call', as: :create_job_call
  resources :insurance_companies
  resources :notes
  get 'job_managers' => 'job_managers#list'
  get 'work_orders' => 'work_orders#list'

  get 'users/:id/job-assignments' => 'users#job_assignments', as: :user_job_assignments
  get 'users/:id/job-assignments/list' => 'users#job_assignments_list', as: :user_job_assignments_list
  get 'jobs/:id/create_estimate' => 'jobs#create_estimate', as: :create_estimate
  get 'jobs/:id/create_estimate_sent' => 'jobs#create_estimate_sent', as: :create_estimate_sent
  get 'jobs/:id/create_contract' => 'jobs#create_contract', as: :create_contract
  get 'jobs/:id/create_contract_sent' => 'jobs#create_contract_sent', as: :create_contract_sent
  get 'pipeline' => 'pipeline#index'
  get 'jobs/new-york-datasheet' => 'jobs#new_york_datasheet', as: :new_york_datasheet

  resources :jobs do
    post 'manager-assignment' => 'jobs#manager_assignment', as: :manager_assignment
    delete 'manager-assignment/:id' => 'jobs#destroy_manager_assignment', as: :destroy_manager_assignment
    post 'caller-assignment' => 'jobs#caller_assignment', as: :caller_assignment
    get 'notes' => 'notes#job_notes'
    get 'overview' => 'overview#index', as: :overview
    get 'loss-sheet' => 'loss_sheet#index', as: :loss_sheet
    get 'reconciliation-form'
    get 'customers/:id' => 'jobs#customer', as: :customer
    resources :ticsheets
    resources :properties
    resources :losses
    resources :callers
    resources :occupants
    resources :job_details
    resources :job_managers
    resources :pricings
    resource :job_coordinator, only: %i(create destroy)
    get 'job_managers/:id/acknolwedge' => 'job_managers#acknolwedge'
    get 'work_orders/:id/acknolwedge' => 'work_orders#acknowledge'
    resources :vendor_assignments
    resources :contact_assignments
    post 'agents/samecaller' => 'agents#samecaller'
    post 'adjusters/samecaller' => 'adjusters#samecaller'
    post 'agents/remove_from_job' => 'agents#remove_from_job', as: :remove_agent
    post 'adjuster/remove_from_job' => 'adjusters#remove_from_job',  as: :remove_adjuster
    post 'customers/samecaller' => 'customers#samecaller', as: :customer_same_as_caller
    resources :emergency_contacts
    post 'emergency_contacts/samecaller' => 'emergency_contacts#samecaller'
    resources :uploads
    get 'job_forms/dowload/:id' => 'job_forms#download'
    resources :job_forms
    get 'job_forms/new/:id' => 'job_forms#new_form', as: :create_form
    resources :work_orders do
      get 'archive', on: :member
      get 'unarchive', on: :member
    end
    resources :schedulers
    resources :subscriptions
    resources :collection_subscriptions, only: [:create, :update, :destroy]
    resources :purchase_order_approvals
    resources :inspection_checklists
  end
  get "move-pricing" => 'pricings#move_to_next', as: :move_to_next

  resources :customers do
    post '/jobs/:job_id' => 'customers#send_to_sharpspring', as: :send_to_sharpspring
  end
  get 'customer_search_suggestions' => 'customers#search_suggestions'
  get 'caller_search_suggestions' => 'callers#search_suggestions'
  post 'customers/:id/calls' => 'customers#create_call', as: :create_customer_call

  post 'jobs/filter' => 'jobs#filter'
  post 'addresses/geolocate' => 'addresses#geolocate'
  post 'agents/lookup' => 'agents#lookup'
  post 'adjusters/lookup' => 'adjusters#lookup'
  get 'share/users', as: :mentionables
  root 'home#index'

  namespace :tsheets do
    resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :datatables do
        resources :jobs, only: :index
        resources :work_orders, only: :index
        resources :calls, only: :index
        resources :users, only: :index
        resources :job_managers, only: :index
      end
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  require 'sidekiq/api'

  match "default-queue-status" => proc { [
    200,
    { "Content-Type" => "text/plain" },
    [Sidekiq::Queue.new("default").size < 20 ? "OK" : "UHOH"]
  ] }, via: :get

  match "mailer-queue-status" => proc { [
    200,
    { "Content-Type" => "text/plain" },
    [Sidekiq::Queue.new("low").size < 20 ? "OK" : "UHOH"]
  ] }, via: :get
end

app/models/ticsheet.rb
class Ticsheet < ActiveRecord::Base
  def self.water_damage_list
    array = [['8010', 'Emerg Service, After HR/Wknd', 'EA'],
             ['8020', 'Emerg Service, Holiday Job', 'EA'],
             ['8200', 'Debris, Disposal', 'BAG'],
             ['8210', 'Debris, Disposal', 'LD'],
             ['9485', 'Labor, General', 'HR'],
             ['9505', 'Labor, On Site Supervision', 'HR'],
             ['1000', 'Ceiling, Remove', 'SF'],
             ['1020', 'Acoustical Tile, Remove', 'SF'],
             ['1030', 'Acoustical Tile Grid, Remove', 'SF'],
             ['1220', 'Insulation, Remove', 'SF'],
             ['1155', 'Ceiling, Antimicrobial', 'SF'],
             ['1155', 'Ceiling, EPA Reg. Disinfectant', 'SF'],
             ['2010', 'Walls, Remove', 'SF'],
             ['1220', 'Insulation, Remove', 'SF'],
             ['2080', 'Wall, EPA Reg. Disinfectant', 'SF'],
             ['2090', 'Wall, Antimicrobial', 'SF'],
             ['3390', 'Carpet, Clean', 'SF'],
             ['3390', 'Carpet, Antimicrobial Pretreat', 'SF'],
             ['3390', 'Carpet, Extraction', 'SF'],
             ['3390', 'Carpet, Extraction, Black', 'SF'],
             ['3390', 'Carpet, Extraction, Gray', 'SF'],
             ['3390', 'Carpet, Extraction, Heavy', 'SF'],
             ['3390', 'Carpet, Antimicrobial', 'SF'],
             ['3390', 'Carpet, Lift', 'SF'],
             ['3390', 'Remove/Cut & Bag', 'SF'],
             ['3390', 'Heavy Soil, Clean', 'SF'],
             ['3390', 'Floor, Clean', 'SF'],
             ['3390', 'Floor, EPA Reg. Disinfectant', 'SF'],
             ['3390', 'Floor, Extraction', 'SF'],
             ['3390', 'Floor, Extraction, Heavy', 'SF'],
             ['3390', 'Floor, Antimicrobial', 'SF'],
             ['3390', 'Floor, Remove', 'SF'],
             ['3390', 'Floor, Hardwood, Clean', 'SF'],
             ['3390', 'Floor, Subfloor, Clean', 'SF'],
             ['3390', 'Floor, Vinyl, Extraction', 'SF'],
             ['3390', 'Floor, Vinyl, Remove', 'SF'],
             ['3390', 'Pad, Remove', 'SF'],
             ['3390', 'Steps, Clean', 'EA'],
             ['3390', 'Steps, Attic, Clean', 'EA'],
             ['3390', 'Steps, Carpeted, Clean', 'EA'],
             ['3390', 'Steps, Hard Surface, Clean', 'EA'],
             ['3390', 'Tackless Strip Remove', 'LF'],
             ['3390', 'Steps, Carpeted, Antimicrobial', 'EA'],
             ['3390', 'Rug, Area, Antimicrobial', 'SF'],
             ['3390', 'Trim, Baseboard, Remove', 'LF'],
             ['3390', 'Trim, Remove', 'LF'],
             ['3390', 'Duct System, Int., Clean', 'EA'],
             ['3390', 'Duct System, Per Opening, Clean', 'EA'],
             ['3390', 'Duct System, Per Register, Clean', 'EA'],
             ['3390', 'Equipment, Setup & Take down', 'EA'],
             ['3390', 'Equipment, Monitor', 'DAY'],
             ['3390', 'Equipment, Clean', 'EA'],
             ['3390', 'Equipment, Decontamination', 'EA'],
             ['3390', 'Air Movers(S), Drying', 'DAY'],
             ['3390', 'Dehumidifier, Small', 'DAY'],
             ['3390', 'Dehumidifier, Larger', 'DAY'],
             ['3390', 'Dehumidifier, Desiccant', 'DAY'],
             ['3390', 'Air Scrubbers, <750 cfm', 'DAY'],
             ['3390', 'Air Scrubbers, 750> cfm', 'DAY'],
             ['3390', 'Personal Protective Eqiup.', 'EA'],
             ['3390', 'Pump, Rental', 'DAY'],
             ['3390', 'Pump, Rental', 'HR'],
             ['3390', 'Generator, Temp Power Contents', 'DAY'],
             ['3390', 'Furniture/Contents - Manipulation', 'HR']
           ]
    return array
  end
end

app/controllers/ticsheets_controller.rb
class TicsheetsController < ApplicationController
  before_action :set_ticsheet, only: [:show, :edit, :update, :destroy]
  before_action :set_job

  # GET /ticsheets
  # GET /ticsheets.json
  def index
    @ticsheets = Ticsheet.all
  end

  # GET /ticsheets/1
  # GET /ticsheets/1.json
  def show
  end

  # GET /ticsheets/new
  def new
    @ticsheet = Ticsheet.new
  end

  # GET /ticsheets/1/edit
  def edit
  end

  # POST /ticsheets
  # POST /ticsheets.json
  def create
    ticsheet_params["key_code"].count.times do |index|
      Ticsheet.create(key_code: ticsheet_params['key_code'][index], description: ticsheet_params['description'][index], uom: ticsheet_params['uom'][index], percentage: ticsheet_params['percentage'][index], quantity: ticsheet_params['quantity'][index])
    end
    respond_to do |format|
      # if @ticsheet.save
        format.html { redirect_to @ticsheet, notice: 'Ticsheet was successfully created.' }
        format.json { render :show, status: :created, location: @ticsheet }
      # else
      #   format.html { render :new }
      #   format.json { render json: @ticsheet.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /ticsheets/1
  # PATCH/PUT /ticsheets/1.json
  def update
    respond_to do |format|
      if @ticsheet.update(ticsheet_params)
        format.html { redirect_to @ticsheet, notice: 'Ticsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticsheet }
      else
        format.html { render :edit }
        format.json { render json: @ticsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticsheets/1
  # DELETE /ticsheets/1.json
  def destroy
    @ticsheet.destroy
    respond_to do |format|
      format.html { redirect_to ticsheets_url, notice: 'Ticsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticsheet
      @ticsheet = Ticsheet.find(params[:id])
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticsheet_params
      params.require(:ticsheet).permit(key_code:[], description:[], uom:[], percentage:[], quantity:[])
    end
end

app/views/ticsheets/_form.html.erb
<%= form_for [@job, @ticsheet] do |f| %>
  <% if @ticsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticsheet.errors.count, "error") %> prohibited this ticsheet from being saved:</h2>

      <ul>
      <% @ticsheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-sm-12">
    <div class="row">
      <div class="col-xs-2">
        <%= f.label :key_code %>
      </div>
      <div class="col-xs-4">
        <%= f.label :description %>
      </div>
      <div class="col-xs-2">
        <%= f.label :uom %>
      </div>
      <div class="col-xs-2">
        <%= f.label :percentage %>
      </div>
      <div class="col-xs-2">
        <%= f.label :quantity %>
      </div>
    </div>
  </div>

<% Ticsheet.water_damage_list.each do |row| %>
  <div class="col-sm-12">
    <div class="row">
      <div class="col-xs-2">
        <%= text_field_tag "ticsheet[key_code][]", row[0], readonly: true, class: "form-control" %>
      </div>
      <div class="col-xs-4">
        <%= text_field_tag "ticsheet[description][]", row[1], readonly: true, class: "form-control" %>
      </div>
      <div class="col-xs-2">
        <%= text_field_tag "ticsheet[uom][]", row[2], readonly: true, class: "form-control"  %>
      </div>
      <div class="col-xs-2">
        <%= text_field_tag "ticsheet[percentage][]", Ticsheet.find_by(job_id: @job.id, key_code: row[0], id: @ticksheet.try(:id)), class: "form-control" %>
      </div>
      <div class="col-xs-2">
        <%= text_field_tag "ticsheet[quantity][]", nil, class: "form-control" %>
      </div>
    </div>
  </div>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticsheets/edit.html.erb
<h1>Editing Ticsheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticsheet %> |
<%= link_to 'Back', ticsheets_path %>

app/views/ticsheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ticsheets</h1>

<table>
  <thead>
    <tr>
      <th>Key code</th>
      <th>Description</th>
      <th>Uom</th>
      <th>Percentage</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticsheets.each do |ticsheet| %>
      <tr>
        <td><%= ticsheet.key_code %></td>
        <td><%= ticsheet.description %></td>
        <td><%= ticsheet.uom %></td>
        <td><%= ticsheet.percentage %></td>
        <td><%= ticsheet.quantity %></td>
        <td><%= link_to 'Show', job_ticsheet_path(@job, ticsheet) %></td>
        <td><%= link_to 'Edit', edit_job_ticsheet_path(@job, ticsheet) %></td>
        <td><%= link_to 'Destroy', job_ticsheet_path(@job, ticsheet), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticsheet', new_job_ticsheet_path %>

app/views/ticsheets/new.html.erb
<h1>New Ticsheet</h1>

<%= render 'form' %>

<%= link_to 'Back', job_ticsheets_path(@job) %>

app/views/ticsheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key code:</strong>
  <%= @ticsheet.key_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticsheet.description %>
</p>

<p>
  <strong>Uom:</strong>
  <%= @ticsheet.uom %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @ticsheet.percentage %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ticsheet.quantity %>
</p>

<%= link_to 'Edit', edit_job_ticsheet_path(@job, @ticsheet) %> |
<%= link_to 'Back', job_ticsheets_path(@job) %>