config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :priorities
  mount Maily::Engine, at: '/maily'
  ActiveAdmin.routes(self)
  resources :customer_vendors
  resources :pricing_categories
  resources :customer_companies
  resources :vehicles
  resources :companies do
    get 'search_suggestions', on: :collection
  end
  resources :notify_types
  resources :notifications
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :upload_categories
  resources :franchise_users
  resources :franchises
  resources :vendor_upload_types
  resources :tracker_tasks
  resources :trackers
  resources :assignment_types
  resources :referral_types
  resources :corporate_referral_types
  resources :contacts
  devise_for :users
  resources :articles
  resources :franchise_zipcodes
  resources :oncalls do
    collection {post :sort}
  end
  resources :forms
  resources :vendor_categories
  resources :vendors do
    resources :vendor_uploads
  end
  resources :phones
  resources :addresses
  resources :calls
  resources :consumables
  resources :chemicals
  post 'calls/precall-lookup' => 'calls#precall_lookup'
  post 'calls/precall-webhook' => 'calls#precall'
  post 'calls/postcall-webhook' => 'calls#postcall'
  get 'users/list' => 'users#list'
  resources :users do
    patch 'link_tsheets_user'
  end
  resources :states
  resources :agents
  resources :adjusters

  get 'adwords' => 'adwords#index'
  get 'jobs/list' => 'jobs#list'
  get 'jobs/for_table' => 'jobs#for_table'
  get 'jobs/index_search' => 'jobs#index_search'
  get 'jobs/search' => 'jobs#search', as: :job_search
  get 'jobs/:id/calls' => 'jobs#calls', as: :job_calls
  get 'jobs/:id/calls/new' => 'jobs#add_call', as: :new_job_call
  post 'jobs/:id/calls' => 'jobs#create_call', as: :create_job_call
  resources :insurance_companies
  resources :notes
  get 'job_managers' => 'job_managers#list'
  get 'work_orders' => 'work_orders#list'

  get 'users/:id/job-assignments' => 'users#job_assignments', as: :user_job_assignments
  get 'users/:id/job-assignments/list' => 'users#job_assignments_list', as: :user_job_assignments_list
  get 'jobs/:id/create_estimate' => 'jobs#create_estimate', as: :create_estimate
  get 'jobs/:id/create_estimate_sent' => 'jobs#create_estimate_sent', as: :create_estimate_sent
  get 'jobs/:id/create_contract' => 'jobs#create_contract', as: :create_contract
  get 'jobs/:id/create_contract_sent' => 'jobs#create_contract_sent', as: :create_contract_sent
  get 'pipeline' => 'pipeline#index'
  get 'jobs/new-york-datasheet' => 'jobs#new_york_datasheet', as: :new_york_datasheet

  resources :jobs do
    post 'manager-assignment' => 'jobs#manager_assignment', as: :manager_assignment
    delete 'manager-assignment/:id' => 'jobs#destroy_manager_assignment', as: :destroy_manager_assignment
    post 'caller-assignment' => 'jobs#caller_assignment', as: :caller_assignment
    get 'notes' => 'notes#job_notes'
    get 'overview' => 'overview#index', as: :overview
    get 'loss-sheet' => 'loss_sheet#index', as: :loss_sheet
    get 'reconciliation-form'
    get 'customers/:id' => 'jobs#customer', as: :customer
    resources :ticsheets
    resources :properties
    resources :losses
    resources :callers
    resources :occupants
    resources :job_details
    resources :job_managers
    resources :pricings
    resource :job_coordinator, only: %i(create destroy)
    get 'job_managers/:id/acknolwedge' => 'job_managers#acknolwedge'
    get 'work_orders/:id/acknolwedge' => 'work_orders#acknowledge'
    resources :vendor_assignments
    resources :contact_assignments
    post 'agents/samecaller' => 'agents#samecaller'
    post 'adjusters/samecaller' => 'adjusters#samecaller'
    post 'agents/remove_from_job' => 'agents#remove_from_job', as: :remove_agent
    post 'adjuster/remove_from_job' => 'adjusters#remove_from_job',  as: :remove_adjuster
    post 'customers/samecaller' => 'customers#samecaller', as: :customer_same_as_caller
    resources :emergency_contacts
    post 'emergency_contacts/samecaller' => 'emergency_contacts#samecaller'
    resources :uploads
    get 'job_forms/dowload/:id' => 'job_forms#download'
    resources :job_forms
    get 'job_forms/new/:id' => 'job_forms#new_form', as: :create_form
    resources :work_orders do
      get 'archive', on: :member
      get 'unarchive', on: :member
    end
    resources :schedulers
    resources :subscriptions
    resources :collection_subscriptions, only: [:create, :update, :destroy]
    resources :purchase_order_approvals
    resources :inspection_checklists
  end
  get "move-pricing" => 'pricings#move_to_next', as: :move_to_next

  resources :customers do
    post '/jobs/:job_id' => 'customers#send_to_sharpspring', as: :send_to_sharpspring
  end
  get 'customer_search_suggestions' => 'customers#search_suggestions'
  get 'caller_search_suggestions' => 'callers#search_suggestions'
  post 'customers/:id/calls' => 'customers#create_call', as: :create_customer_call

  post 'jobs/filter' => 'jobs#filter'
  post 'addresses/geolocate' => 'addresses#geolocate'
  post 'agents/lookup' => 'agents#lookup'
  post 'adjusters/lookup' => 'adjusters#lookup'
  get 'share/users', as: :mentionables
  root 'home#index'

  namespace :tsheets do
    resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :datatables do
        resources :jobs, only: :index
        resources :work_orders, only: :index
        resources :calls, only: :index
        resources :users, only: :index
        resources :job_managers, only: :index
      end
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  require 'sidekiq/api'

  match "default-queue-status" => proc { [
    200,
    { "Content-Type" => "text/plain" },
    [Sidekiq::Queue.new("default").size < 20 ? "OK" : "UHOH"]
  ] }, via: :get

  match "mailer-queue-status" => proc { [
    200,
    { "Content-Type" => "text/plain" },
    [Sidekiq::Queue.new("low").size < 20 ? "OK" : "UHOH"]
  ] }, via: :get
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @active_leads = Job.where(job_status: 1).count
    @active_jobs = Job.where(job_status: 2).count
    @month_calls = Call.where(created_at: Time.now.beginning_of_month..Time.now.end_of_month).count
    @ongoing_calls = Call.where(inprogress: true).count


    @activities = PublicActivity::Activity.all

    if current_user.admin? || current_user.owner?
      @jobs = Job.where(entered_by_id: current_user.id).where("status_id= ? OR status_id= ?", 1, 2)
      render template: 'home/admin'
    elsif current_user.job_coordinator? || current_user.unassigned?
      @jobs = Job.where(entered_by_id: current_user.id).where("status_id= ? OR status_id= ?", 1, 2)
      render template: 'home/job_coordinator'
    elsif current_user.call_rep?
      render template: 'home/call_rep'
    elsif current_user.collections?
      render template: 'home/collections'
    elsif current_user.project_manager?
      @jobs = Job.with_manager_id(current_user.id)
      render template: 'home/project_manager'
    elsif current_user.contractor?
      @jobs = Job.eager_load(:subscriptions).where("subscriptions.user_id= ?", current_user.id)
      render template: 'home/contractor'
    elsif current_user.technician?
      render template: 'home/technician'
    elsif current_user.crew_chief?
      render template: 'home/crew_chief'
    end
  end
end

app/views/home/admin.html.erb
<div class="container-fluid">

  <section id="home">

    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header text-center">Dashboard</h1>
      </div>
    </div>
    <!--/.row-->

    <div class="row">
      <div class="col-xs-12 col-md-6 col-lg-3">
        <div class="panel panel-blue panel-widget ">
          <div class="row no-padding">
            <div class="col-sm-3 col-lg-5 widget-left">
              <i class="glyph-dash glyphicon glyphicon-star-empty" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-lg-7 widget-right">
              <div class="large"><%= @active_leads %></div>
              <div class="text-muted">Active Leads</div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-3">
        <div class="panel panel-orange panel-widget">
          <div class="row no-padding">
            <div class="col-sm-3 col-lg-5 widget-left">
              <i class="glyph-dash glyphicon glyphicon-star" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-lg-7 widget-right">
              <div class="large"><%= @active_jobs %></div>
              <div class="text-muted">Active Jobs</div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-3">
        <div class="panel panel-teal panel-widget">
          <div class="row no-padding">
            <div class="col-sm-3 col-lg-5 widget-left">
              <i class="glyph-dash glyphicon glyphicon-earphone" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-lg-7 widget-right">
              <div class="large"><%= @month_calls %></div>
              <div class="text-muted">Calls (Monthly)</div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-6 col-lg-3">
        <div class="panel panel-red panel-widget">
          <div class="row no-padding">
            <div class="col-sm-3 col-lg-5 widget-left">
              <i class="glyph-dash glyphicon glyphicon-earphone" aria-hidden="true"></i>
            </div>
            <div class="col-sm-9 col-lg-7 widget-right">
              <div class="large"><%= @ongoing_calls %></div>
              <div class="text-muted">In Progress Calls</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">Jobs</div>
          <div class="panel-body">
            <%= render partial: 'datatables/jobs', locals: {
              columns: [
                :name,
                :job_status_name,
                :customer_full_name,
                :claim_number,
                :job_loss_type_name,
                :insurance_company_name,
                :created_at
              ]}
            %>
        </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">Users</div>
          <div class="panel-body">
            <%= render partial: 'datatables/users', locals: {
              columns: [
                :id,
                :first_name,
                :last_name,
                :department_name
              ]}
            %>
        </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">Job Manager Assignments</div>
          <div class="panel-body">
            <%= render partial: 'datatables/job_managers', locals: {
              columns: [
                :user_id,
                :first_name,
                :last_name,
                :job_id,
                :job_name,
                :schedule_date,
                :manager_confirmation
              ]}
            %>
        </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">Dead Leads (7 days or more with no activity)</div>
          <div class="panel-body">
            <%= render partial: 'datatables/jobs', locals: {
              filter: 'no_activity=true',
              columns: [
                :name,
                :job_status_name,
                :customer_full_name,
                :claim_number,
                :job_loss_type_name,
                :insurance_company_name,
                :created_at
              ]}
            %>
        </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">Work Orders Created</div>
          <div class="panel-body">
            <%= render partial: 'datatables/work_orders', locals: {
              columns: [
                :created_at,
                :id,
                :state,
                :job_id,
                :job_name,
                :contact,
              ]}
            %>
        </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">Jobs Created By Call Reps</div>
          <div class="panel-body">
            <%= render partial: 'datatables/jobs', locals: {
              filter: 'call_rep_jobs=true',
              columns: [
                :name,
                :job_status_name,
                :customer_full_name,
                :claim_number,
                :job_loss_type_name,
                :insurance_company_name,
                :created_at
              ]}
            %>
        </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="panel panel-default">
          <div class="panel-heading">Jobs without Coorindator</div>
          <div class="panel-body">
            <%= render partial: 'datatables/jobs', locals: {
              filter: 'unassigned=true',
              columns: [
                :name,
                :job_status_name,
                :customer_full_name,
                :claim_number,
                :job_loss_type_name,
                :insurance_company_name,
                :created_at
              ]}
            %>
        </div>
        </div>
      </div>
    </div>


<div class="col-md-8 col-md-offset-2">
<% unless @jobs.empty? %>
<% @jobs.each do |job| %>
<%
	job_array = job.trackers.sort_by{|x| x.created_at}
	%>
<div class="panel panel-default">
	<div class="panel-heading">
		Job ID: <%= link_to job.id, job_path(job) %>
	</div>
	<div class="panel-body">
		Progress:
		<div class="progress">
			<div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="<%= job.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= job.progress %>%"></div>
		</div>
		<div class="row">

			<div class="timeline-centered">
				<% job_array.each do |tracker| %>
				<article class="timeline-entry">
					<div class="timeline-entry-inner">
						<div class="timeline-icon bg-success">
							<i class="entypo-feather"></i>
						</div>
						<div class="timeline-label">
							<h2>
								<%= link_to tracker_link_to(tracker.tracker_task_id, tracker.trackable_id) do %>
								<%= tracker.tracker_task.name %>
								<% end %>
							</span>
						</h2>
						<% if tracker.tracker_task_id == 2 %>
							<% @job_manager = tracker.child_trackable %>
								Manager: <%= @job_manager.try(:job_manager).try(:full_name) %><br />
								Scheduled Date: <%= @job_manager.try(:schedule_date) %>
						<% end %>
						<p>Date:
							<%= tracker.created_at %></p>
					</div>

				</div>
			</article>
			<% end %>
			<div class="next-step text-center">


			<% if job_array.last.try(:tracker_task_id) %>
				<%= link_to job_array.last.try(:next_step_task),  next_step_link(job_array.last.tracker_task_id, job_array.last.trackable_id), class: "btn btn-primary" %>
			<% end %>
			</div>
		</div>
	</div>
</div>
</div>
<% end %>
<% end %>
</div>

</div>

app/views/home/call_rep.html.erb
<section id="home">

	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header text-center">Dashboard</h1>
		</div>
	</div>
	<!--/.row-->

	<div class="row">
		<%= link_to new_job_path do %>
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-blue panel-widget ">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-plus" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">New Call</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
		<%= link_to job_search_path do %>
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-red panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-search" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Log Book</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-orange panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Wiki</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--/.main-->
</section>

app/views/home/crew_chief.html.erb
<div class="container-fluid">

	<section id="home">
			<div class="row">

			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">Work Orders Created</div>
					<div class="panel-body">
						<table
							data-toggle="table"
							data-url="/work_orders.json"
							data-show-refresh="true"
							data-show-toggle="true"
							data-show-columns="true"
							data-search="true"
							data-flat="true"
							data-select-item-name="toolbar1"
							data-pagination="true"
							data-sort-name="id"
							data-sort-order="desc">
							<thead>
								<tr>
									<th data-field="id" data-formatter="WorkOrderLinkFormatter" data-sort-order='desc' data-sortable="true">Word Order ID</th>
									<th data-field="job_id" data-formatter="JobLinkFormatter" data-sortable="true">Job ID</th>
									<th data-field="created_at"  data-sortable="true">Created At<th>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</div>
		</section>
	</div>

</div>

app/views/home/job_coordinator.html.erb
<div class="container-fluid">
<section id="home">

	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header text-center">Dashboard</h1>
		</div>
	</div>
	<!--/.row-->

	<div class="row">
		<%= link_to new_job_path do %>
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-blue panel-widget ">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-plus" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">New Call</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
		<%= link_to jobs_path do %>
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-red panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-search" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Log Book</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
		<%= link_to articles_path do %>
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-orange panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-search" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Wiki</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<h2 class="text-center">Work Center</h2>
		</div>
		<a href="https://workcenter.sso.servpronet.com/Office/JobManagement" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-orange panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Job Management Dashboard</div>
					</div>
				</div>
			</div>
		</div>
		</a>

		<a href="https://workcenters.sso.servpronet.com/dashboards/officeoperations" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-blue panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Office Operations Dashboard</div>
					</div>
				</div>
			</div>
		</div>
		</a>

		<a href="https://workcenters.sso.servpronet.com/dashboards/activejobs" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-red panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Active Jobs Dashboard</div>
					</div>
				</div>
			</div>
		</div>
		</a>


		<a href="https://workcenters.sso.servpronet.com/dashboards/completedjobs" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-orange panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Completed Jobs Dashboard</div>
					</div>
				</div>
			</div>
		</div>
		</a>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<h2 class="text-center">Other Links</h2>
		</div>


		<a href="https://servpromedfordny.tsheets.com/page/login" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-blue panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">TSheets</div>
					</div>
				</div>
			</div>
		</div>
		</a>

		<a href="https://cam.sso.servpronet.com/RSTS/Login?wa=wsignin1.0&wtrealm=urn%3acam.sso.servpronet.com%2fCloudAccessManager%2fRPSTS&wreply=https%3a%2f%2fcam.sso.servpronet.com%2fCloudAccessManager%2fRPSTS%2fWSFed%2fLogin.aspx&primaryProviderID=ActiveDirectory_6" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-red panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">SERVPRO NET </div>
					</div>
				</div>
			</div>
		</div>
		</a>

		<a href="https://apps.xactware.com/apps/cxa/start.jsp" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-orange panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Xactanalysis</div>
					</div>
				</div>
			</div>
		</div>
		</a>

		<a href="https://app.callrail.com/a/686639065/copilot/" target="_blank">
		<div class="col-xs-12 col-md-6 col-lg-4">
			<div class="panel panel-blue panel-widget">
				<div class="row no-padding">
					<div class="col-sm-3 col-lg-5 widget-left">
						<i class="glyph-dash glyphicon glyphicon-info-sign" aria-hidden="true"></i>
					</div>
					<div class="col-sm-9 col-lg-7 widget-right">
						<div class="large">Copilot</div>
					</div>
				</div>
			</div>
		</div>
		</a>

	</div>

	<div class="row">
		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-heading">Jobs Created By Call Reps</div>
				<div class="panel-body">
          <%= render partial: 'datatables/jobs', locals: {
            filter: 'call_rep_jobs=true',
            columns: [
              :name,
              :job_status_name,
              :customer_full_name,
              :claim_number,
              :job_loss_type_name,
              :insurance_company_name,
              :created_at
            ]}
          %>
				</div>
			</div>
		</div>

		<div class="col-lg-6">
			<div class="panel panel-default">
				<div class="panel-heading">Jobs without Coorindator</div>
				<div class="panel-body">
          <%= render partial: 'datatables/jobs', locals: {
            filter: 'unassigned=true',
            columns: [
              :name,
              :job_status_name,
              :customer_full_name,
              :claim_number,
              :job_loss_type_name,
              :insurance_company_name,
              :created_at
            ]}
          %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
		<% unless @jobs.empty? %>
		<% @jobs.each do |job| %>
		<%
			job_array = job.trackers.sort_by{|x| x.created_at}
			%>
		<div class="panel panel-default">
			<div class="panel-heading">
				<% if job.name != nil %>
					Job Name: <%= link_to job.name, job_path(job) %>
				<% else %>
					Job ID: <%= link_to job.id, job_path(job) %>
				<% end %>
			</div>
			<div class="panel-body">
				Progress:
				<div class="progress">
					<div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="<%= job.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= job.progress %>%"></div>
				</div>
				<div class="row">

					<div class="timeline-centered">
						<% job_array.each do |tracker| %>
						<article class="timeline-entry">
							<div class="timeline-entry-inner">
								<div class="timeline-icon bg-success">
									<i class="entypo-feather"></i>
								</div>
								<div class="timeline-label">
									<h2>
										<%= link_to tracker_link_to(tracker.tracker_task_id, tracker.trackable_id) do %>
										<%= tracker.tracker_task.name %>
										<% end %>
									</span>
								</h2>
								<% if tracker.tracker_task_id == 2 %>
									<% @job_manager = tracker.child_trackable %>
										Manager: <%= @job_manager.try(:job_manager).try(:full_name) %><br />
										Scheduled Date: <%= @job_manager.try(:schedule_date) %>
								<% end %>
								<p>Date:
									<%= tracker.created_at %></p>
							</div>

						</div>
					</article>
					<% end %>
					<div class="next-step text-center">


					<% if job_array.last.try(:tracker_task_id) %>
						<%= link_to job_array.last.try(:next_step_task),  next_step_link(job_array.last.tracker_task_id, job_array.last.trackable_id), class: "btn btn-primary" %>
					<% end %>
					</div>
				</div>
			</div>
		</div>
		</div>
		<% end %>
		<% end %>
		</div>
	</div>
</div>
<!--/.main-->
</section>

</div>