config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :priorities
  mount Maily::Engine, at: '/maily'
  ActiveAdmin.routes(self)
  resources :customer_vendors
  resources :pricing_categories
  resources :customer_companies
  resources :vehicles
  resources :companies do
    get 'search_suggestions', on: :collection
  end
  resources :notify_types
  resources :notifications
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :upload_categories
  resources :franchise_users
  resources :franchises
  resources :vendor_upload_types
  resources :tracker_tasks
  resources :trackers
  resources :assignment_types
  resources :referral_types
  resources :corporate_referral_types
  resources :contacts
  devise_for :users
  resources :articles
  resources :franchise_zipcodes
  resources :oncalls do
    collection {post :sort}
  end
  resources :forms
  resources :vendor_categories
  resources :vendors do
    resources :vendor_uploads
  end
  resources :phones
  resources :addresses
  resources :calls
  resources :consumables
  resources :chemicals
  post 'calls/precall-lookup' => 'calls#precall_lookup'
  post 'calls/precall-webhook' => 'calls#precall'
  post 'calls/postcall-webhook' => 'calls#postcall'
  get 'users/list' => 'users#list'
  resources :users do
    patch 'link_tsheets_user'
  end
  resources :states
  resources :agents
  resources :adjusters

  get 'adwords' => 'adwords#index'
  get 'jobs/list' => 'jobs#list'
  get 'jobs/for_table' => 'jobs#for_table'
  get 'jobs/index_search' => 'jobs#index_search'
  get 'jobs/search' => 'jobs#search', as: :job_search
  get 'jobs/:id/calls' => 'jobs#calls', as: :job_calls
  get 'jobs/:id/calls/new' => 'jobs#add_call', as: :new_job_call
  post 'jobs/:id/calls' => 'jobs#create_call', as: :create_job_call
  resources :insurance_companies
  resources :notes
  get 'job_managers' => 'job_managers#list'
  get 'work_orders' => 'work_orders#list'

  get 'users/:id/job-assignments' => 'users#job_assignments', as: :user_job_assignments
  get 'users/:id/job-assignments/list' => 'users#job_assignments_list', as: :user_job_assignments_list
  get 'jobs/:id/create_estimate' => 'jobs#create_estimate', as: :create_estimate
  get 'jobs/:id/create_estimate_sent' => 'jobs#create_estimate_sent', as: :create_estimate_sent
  get 'jobs/:id/create_contract' => 'jobs#create_contract', as: :create_contract
  get 'jobs/:id/create_contract_sent' => 'jobs#create_contract_sent', as: :create_contract_sent
  get 'pipeline' => 'pipeline#index'
  get 'jobs/new-york-datasheet' => 'jobs#new_york_datasheet', as: :new_york_datasheet

  resources :jobs do
    post 'manager-assignment' => 'jobs#manager_assignment', as: :manager_assignment
    delete 'manager-assignment/:id' => 'jobs#destroy_manager_assignment', as: :destroy_manager_assignment
    post 'caller-assignment' => 'jobs#caller_assignment', as: :caller_assignment
    get 'notes' => 'notes#job_notes'
    get 'overview' => 'overview#index', as: :overview
    get 'loss-sheet' => 'loss_sheet#index', as: :loss_sheet
    get 'reconciliation-form'
    get 'customers/:id' => 'jobs#customer', as: :customer
    resources :ticsheets
    resources :properties
    resources :losses
    resources :callers
    resources :occupants
    resources :job_details
    resources :job_managers
    resources :pricings
    resource :job_coordinator, only: %i(create destroy)
    get 'job_managers/:id/acknolwedge' => 'job_managers#acknolwedge'
    get 'work_orders/:id/acknolwedge' => 'work_orders#acknowledge'
    resources :vendor_assignments
    resources :contact_assignments
    post 'agents/samecaller' => 'agents#samecaller'
    post 'adjusters/samecaller' => 'adjusters#samecaller'
    post 'agents/remove_from_job' => 'agents#remove_from_job', as: :remove_agent
    post 'adjuster/remove_from_job' => 'adjusters#remove_from_job',  as: :remove_adjuster
    post 'customers/samecaller' => 'customers#samecaller', as: :customer_same_as_caller
    resources :emergency_contacts
    post 'emergency_contacts/samecaller' => 'emergency_contacts#samecaller'
    resources :uploads
    get 'job_forms/dowload/:id' => 'job_forms#download'
    resources :job_forms
    get 'job_forms/new/:id' => 'job_forms#new_form', as: :create_form
    resources :work_orders do
      get 'archive', on: :member
      get 'unarchive', on: :member
    end
    resources :schedulers
    resources :subscriptions
    resources :collection_subscriptions, only: [:create, :update, :destroy]
    resources :purchase_order_approvals
    resources :inspection_checklists
  end
  get "move-pricing" => 'pricings#move_to_next', as: :move_to_next

  resources :customers do
    post '/jobs/:job_id' => 'customers#send_to_sharpspring', as: :send_to_sharpspring
  end
  get 'customer_search_suggestions' => 'customers#search_suggestions'
  get 'caller_search_suggestions' => 'callers#search_suggestions'
  post 'customers/:id/calls' => 'customers#create_call', as: :create_customer_call

  post 'jobs/filter' => 'jobs#filter'
  post 'addresses/geolocate' => 'addresses#geolocate'
  post 'agents/lookup' => 'agents#lookup'
  post 'adjusters/lookup' => 'adjusters#lookup'
  get 'share/users', as: :mentionables
  root 'home#index'

  namespace :tsheets do
    resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :datatables do
        resources :jobs, only: :index
        resources :work_orders, only: :index
        resources :calls, only: :index
        resources :users, only: :index
        resources :job_managers, only: :index
      end
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  require 'sidekiq/api'

  match "default-queue-status" => proc { [
    200,
    { "Content-Type" => "text/plain" },
    [Sidekiq::Queue.new("default").size < 20 ? "OK" : "UHOH"]
  ] }, via: :get

  match "mailer-queue-status" => proc { [
    200,
    { "Content-Type" => "text/plain" },
    [Sidekiq::Queue.new("low").size < 20 ? "OK" : "UHOH"]
  ] }, via: :get
end

app/models/franchise_zipcode.rb
class FranchiseZipcode < ActiveRecord::Base
  belongs_to :franchise, required: true

  validates_uniqueness_of :zip_code, conditions: -> { assigned }

  scope :assigned, -> { where(assigned: true) }

  delegate :name, to: :franchise, allow_nil: true, prefix: true

  def self.detect_franchise(zipcode)
    assigned.where(zip_code: zipcode).pluck(:franchise_id).first
  end
end

app/controllers/franchise_zipcodes_controller.rb
class FranchiseZipcodesController < ApplicationController
  before_action :set_franchise_zipcode, only: [:show, :edit, :update, :destroy]

  # GET /franchise_zipcodes
  # GET /franchise_zipcodes.json
  def index
    @franchise_zipcodes = FranchiseZipcode.includes(:franchise).order('franchises.name, zip_code').all
  end

  # GET /franchise_zipcodes/1
  # GET /franchise_zipcodes/1.json
  def show
  end

  # GET /franchise_zipcodes/new
  def new
    @franchise_zipcode = FranchiseZipcode.new
  end

  # GET /franchise_zipcodes/1/edit
  def edit
  end

  # POST /franchise_zipcodes
  # POST /franchise_zipcodes.json
  def create
    @franchise_zipcode = FranchiseZipcodeForm.call(franchise_zipcode_params)

    respond_to do |format|
      if @franchise_zipcode.save
        format.html { redirect_to @franchise_zipcode, notice: 'Franchise zipcode was successfully created.' }
        format.json { render :show, status: :created, location: @franchise_zipcode }
      else
        format.html { render :new }
        format.json { render json: @franchise_zipcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /franchise_zipcodes/1
  # PATCH/PUT /franchise_zipcodes/1.json
  def update
    respond_to do |format|
      if @franchise_zipcode.update(franchise_zipcode_params)
        format.html { redirect_to @franchise_zipcode, notice: 'Franchise zipcode was successfully updated.' }
        format.json { render :show, status: :ok, location: @franchise_zipcode }
      else
        format.html { render :edit }
        format.json { render json: @franchise_zipcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /franchise_zipcodes/1
  # DELETE /franchise_zipcodes/1.json
  def destroy
    @franchise_zipcode.destroy
    respond_to do |format|
      format.html { redirect_to franchise_zipcodes_url, notice: 'Franchise zipcode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_franchise_zipcode
      @franchise_zipcode = FranchiseZipcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def franchise_zipcode_params
      params.require(:franchise_zipcode).permit(:franchise_id, :zip_code, :city, :county, :assigned, :county_rate, :city_rate, :special_rate, :local_tax_total) 
    end
end

app/views/franchise_zipcodes/_form.html.slim
= simple_form_for(@franchise_zipcode) do |f|
  = render partial: 'partials/model_errors', locals: {model: @franchise_zipcode}

  .form-inputs
    = f.input :franchise_id, type: :select, collection: Franchise.order(:name)
    = f.input :zip_code
    = f.input :city
    = f.input :county
    = f.input :assigned
    = f.input :county_rate
    = f.input :city_rate
    = f.input :special_rate
    = f.input :local_tax_total

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/franchise_zipcodes/edit.html.slim
- content_for(:title, "Editing Franchise Zip Code")

== render layout: 'layouts/content'
  == render 'form'

  => link_to 'Show', @franchise_zipcode, class: 'btn btn-primary'
  =< link_to 'Back', franchise_zipcode_path, class: 'btn btn-default'

app/views/franchise_zipcodes/index.html.slim
-content_for(:title, 'franchise_zipcodes')

== render layout: 'layouts/content'
  .text-right
    = link_to 'New Franchise Zipcode', new_franchise_zipcode_path, class: 'btn btn-success'
  br

  .table-responsive
    table.table.table-striped.jambo_table
      thead
        tr.headings
          th Franchise Assigned
          th Zipcode
          th City
          th County
          th Assigned
          th

      tbody
        - @franchise_zipcodes.each do |franchise_zipcode|
          tr
            td = franchise_zipcode.franchise_name
            td = franchise_zipcode.zip_code
            td = franchise_zipcode.city
            td = franchise_zipcode.county
            td = franchise_zipcode.assigned
            td.text-right
              = link_to 'Show', franchise_zipcode, class: 'btn btn-xs btn-primary'
              = link_to 'Edit', edit_franchise_zipcode_path(franchise_zipcode), class: 'btn btn-xs btn-success'
              = link_to 'Destroy', franchise_zipcode, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-xs btn-danger'

app/views/franchise_zipcodes/new.html.slim
- content_for(:title, "New Franchise Zipcode")

== render layout: 'layouts/content'
  == render 'form'

  = link_to 'Back', franchise_zipcodes_path, class: 'btn btn-default'

app/views/franchise_zipcodes/show.html.slim
- content_for(:title, "Franchise Zipcode")

== render layout: 'layouts/content'
  p#notice = notice

  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong Franchise Assigned:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcode.franchise_id
  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong Zipcode:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcode.zip_code
  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong City:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcode.city
  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong County:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcode.county
  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong Assigned:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcode.assigned
  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong County Rate:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcodes.county_rate
  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong City Rate:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcodes.city_rate
  .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong Special Rate:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcodes.special_rate
    .row
    .col-md-3.col-sm-3.col-xs-12.text-right
      strong Local Tax Total:
    .col-md-6.col-sm-6.col-xs-12
      = @franchise_zipcodes.local_tax_total

  .text-center
    => link_to 'Edit', edit_franchise_zipcode_path(@franchise_zipcode), class: 'btn btn-primary'
    =< link_to 'Back', franchise_zipcodes_path, class: 'btn btn-default'